# Generated by Django 4.1.7 on 2023-03-01 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='employees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Email', models.EmailField(max_length=254)),
                ('Password', models.CharField(max_length=10)),
                ('age', models.PositiveIntegerField()),
                ('salary', models.FloatField()),
                ('Joining_Date', models.DateField()),
                ('Created_at', models.DateTimeField(auto_now_add=True)),
                ('Upadate_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
