# Generated by Django 4.1.7 on 2023-03-01 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pName', models.CharField(max_length=100)),
                ('pDescription', models.CharField(max_length=100)),
                ('pColor', models.CharField(max_length=20)),
                ('pPrice', models.FloatField()),
                ('pQuantity', models.PositiveIntegerField()),
                ('pAvalibility', models.BooleanField(default=True)),
                ('Last_Updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
