# Generated by Django 4.1.7 on 2023-03-09 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batches', '0002_alter_faculty_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty',
            name='gender',
            field=models.CharField(choices=[('Male', 'male'), ('Female', 'Female')], max_length=100),
        ),
    ]
